/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface LoadingSpinner {
    'color': string;
    'type': string;
  }
  interface LoadingSpinnerAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LoadingSpinner': Components.LoadingSpinner;
  }

  interface StencilIntrinsicElements {
    'loading-spinner': Components.LoadingSpinnerAttributes;
  }


  interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {}
  var HTMLLoadingSpinnerElement: {
    prototype: HTMLLoadingSpinnerElement;
    new (): HTMLLoadingSpinnerElement;
  };

  interface HTMLElementTagNameMap {
    'loading-spinner': HTMLLoadingSpinnerElement
  }

  interface ElementTagNameMap {
    'loading-spinner': HTMLLoadingSpinnerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
